### ISSUE TITLE
Add Support for Python 3 and Add CI for Python 3

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/dragonfly#12]
As a core library, this should work in both Python 2 and Python 3.

**Comment by AntoineDao** [comment]
Happy to pick this one up over the next week if you want. I'm already warmed up from setting it up for UWG :)

**Comment by chriswmackey** [comment]
@antoinedao ,
That would be great. Once I'm in Australia by Friday, there will be a pause in my changes for a few days and that will be great to put in Python 3 compatibility.

**Comment by chriswmackey** [comment]
@AntoineDao ,

I have finished the major refactoring of the core and I don't plan on touching this repo for at least a week now.  If you want to go ahead and add in Python3 support and Python3 CI, the next few days would be a good time to do so.

**Comment by AntoineDao** [comment]
Nice one. Sounds like a plan!
