### ISSUE TITLE
Add a UWGRunManager Class for the Core

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/dragonfly#14]
I know that this is not the cleanest solution right now but I feel that this is necessary to get a minimum version of the core working.  All of the code that is currently within the RunUWG component will go there and this will undoubtedly have to be revised as the interface with the UWG becomes cleaner.

**Comment by chriswmackey** [comment]
@AntoineDao ,
I just wanted to let you know that, after the update to Python 3, this is the only other issue that I want to address before pushing to PiPy and giving you the thumbs up on a pure python demo video of dragonfly.

This is basically going to take the code inside the runUWG component and wrap it in an object.  It won't be very elegant code but I think that this is necessary to enable ease of use of running dragonfly objects through the UWG.

**Comment by AntoineDao** [comment]
Great! I'd be happy to do a quick review of it for you before you merge your PR if you want to see if there are ways to make it a bit more elegant. Let me know when your PR's ready and I'll probably use that as the basis for Python 3 cleanup also.

**Comment by chriswmackey** [comment]
Thanks @AntoineDao .  I'll try to take a pass at this soon.

**Comment by chriswmackey** [comment]
@AntoineDao ,

This is now done!  You have the green light to deploy this to PiPy whenever you like.  Just make sure that it's under ladybug tools as the author and the package name is `lbt-dragonfly`.

Also, before you make your tutorial video showing how to use dragonfly in cPython, make sure to check out the [now elegantly simple code to run the UWG from Dragonfly](https://github.com/ladybug-tools/dragonfly/blob/master/README.md).  I think this will be a lot easier than what you were likely using in Malaga.

One more note: I think I will try rolling out some API docs shortly (not sure if you want to show that in your video).

Lastly, I will start working on the Dragonfly[+] plugin for Grasshopper on my flight back from Australia.  I don't think that this should hold up your videos for that one but just know that this will be coming soon.

**Comment by AntoineDao** [comment]
Just in time for me to hand in that essay to Cost Restore! I am mostly aiming to write a short blog post/1000 word essay taking people through the process all in Python. I suspect a video might be a bit over kill for what I had in mind. Might also add in an experimantal `from_open_street_map` class method for the tutorial. We can make the method better in the future but I suspect the abstraction will be the same right? (eg: `typology1 = Typology.from_open_street_map(osm_coords, osm_server, osm_building_type, bldg_program, bldg_era, floor_to_floor)`)

**Comment by chriswmackey** [comment]
@AntoineDao ,

Blog post sounds good. If parts of your post are going to be useful far into the future, we might also want to copy some of it to the Wiki section on this repo.

For the `from_open_street_map` method, I am thinking that I will add objects that represent the building floor curves that act as children to the Typology class.  This will have some dependencies on [ladybug-geometry](https://github.com/ladybug-tools/ladybug-geometry) and will generally make it a lot easier to go from geojson or openstreetmap formats.  While I'm not sure that I will get the geometry methods done on my flight, I am planing to add these classes on the flight to make it easier to set up the Grasshopper plugin.  So it might be worth waiting just a few more days if you want to demo that.

Also, I added a first pass at the api documentation:
http://www.ladybug.tools/apidoc/dragonfly/
